### ISSUE TITLE
Actualización a odoo 14

### ISSUE THREAD

**Issue by Johnrivera7** [intellego-bi/odoo-cl-12#15]
¿Existe la posibilidad de migrar a 14 y luego 16? 

¿En que te puedo colaborar?

**Comment by Johnrivera7** [comment]
@intellego-rbn

**Comment by intellego-rbn** [comment]
Hola, dejamos  Odoo de lado por no haber podido encontrar Partners adecuados en la región,  pero si quieres tomar la bututa te apoyamos en lo que podamos!

**Comment by dodecap** [comment]
Hola, soy DOmingo estoy partiendo con Odoo como partner. Necesito RRHH para 16, la próxima semana comienzo con el curso de sh. Que consejo me darian para continuar con el proyecto que esta disponible??

**Comment by intellego-rbn** [comment]
El mejor consejo: busca una buen partner!

**Comment by intellego-rbn** [comment]
> ¿Existe la posibilidad de migrar a 14 y luego 16?
> 
> ¿En que te puedo colaborar?

Estamos retomando el proyecto Odoo, empezando por migrar todo este repo a la versión 16.0.
